<li>
					<a href="[field:arcurl/]" target="_blank" title="[field:title/]">
						<i class="num num-1">1</i>
						[field:title/]
					</a>
					<div class="new_share">
						<div class="share_desc share_time">
							<span>[field:pubdate function="tranTime(@me)" /]</span>
						</div>
						<div class="share_desc share_way">
							<span>分享至</span>
							<div class="weixin">
								<div class="code_desc">
									<div class="code_img">
										<img src="img/code.png">
									</div>
									<div class="code_note">
										<p>打开微信扫一扫</p>
									</div>
								</div>
							</div>
							<div class="weibo"></div>
						</div>
					</div>
				</li>