<li>
                <i class="dot"></i>
            	<a href="[field:arcurl/]" target="_blank"><span class="title">[field:title/]</span></a>
            	<div class="new_share">
					<div class="share_desc share_time">
						<span>[field:pubdate function="tranTime(@me)" /]</span>
					</div>
					<div class="share_desc share_way">
						<span>分享至</span>
						<div class="weixin weixin_top">
						<div class="code_top type_one">
							<div class="code_img">
								<img src="img/code.png">
							</div>
							<div class="code_note">
								<p>打开微信扫一扫</p>
							</div>
						</div>
					</div>
						<div class="weibo"></div>
					</div>
				</div>
            </li>