<?php
$z[0]=Array("arcurl","",55,70);
$z[0][4]=array();
$z[1]=Array("litpic","",94,109);
$z[1][4]=array();
$z[2]=Array("title","",116,130);
$z[2][4]=array();
$z[3]=Array("arcurl","",165,180);
$z[3][4]=array();
$z[4]=Array("description","",224,274);
$z[4][4]=array();
$z[4][4]['function']="cn_substr(@me,250)";
$z[5]=Array("pubdate","",381,428);
$z[5][4]=array();
$z[5][4]['function']="MyDate('Y-m-d',@me)";

?>