<div class="item-subject">
			<a href="[field:arcurl/]" class="img"><img src="[field:litpic/]" alt="[field:title/]"></a>		<h3 class="title"><a href="[field:arcurl/]">[field:title/]</a></h3>
			<p class="desc">[field:description function='cn_substr(@me,250)'/]</p>
			<div class="attr">
							<span class="attr-time">[field:pubdate function="tranTime(@me)" /]</span>
				<a href="http://www.wabei.cn/tag/40101/" class="tag" target="_blank">[field:id function=GetTags(@me)/]</a>
			</div>
		</div>