<div class="item-subject item-subject-hot">
		<a href="[field:arcurl/]" class="img"><img src="[field:litpic/]" alt="[field:title/]"></a>		<h3 class="title"><a href="[field:arcurl/]">[field:title/]</a></h3>
		<p class="desc">[field:description function='cn_substr(@me,250)'/]...</p>
		<div class="attr">
			<span class="attr-author">[field:writer/]</span>			<span class="attr-time">[field:pubdate function="MyDate('Y-m-d',@me)"/]</span>
			<a href="" class="tag" target="_blank">{dede:tag type='current'/}</a>
		
		</div>
	</div>