<?php
$z[0]=Array("channel","\n			<li class=\"nav-item\" data-attr=\"133\"><a class=\"nav-item-link\" href=\"[field:typeurl/]\">[field:typename/]</a></li>\n			",1928,2097);
$z[0][4]=array();
$z[0][4]['type']="top";
$z[0][4]['row']="10";
$z[1]=Array("arclist","\n				<div class=\"item-subject item-subject-hot\">\n					<a href=\"[field:arcurl/]\" class=\"img\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\"></a>		<h3 class=\"title\"><a href=\"[field:arcurl/]\">[field:title/]</a></h3>\n					<p class=\"desc\">[field:description function='cn_substr(@me,250)'/]...</p>\n					<div class=\"attr\">\n						<span class=\"attr-author\">[field:writer/]</span>			<span class=\"attr-time\">[field:pubdate function=\"tranTime(@me)\" /]</span>\n						[field:id function=GetTags(@me)/]\n					</div>\n				</div>\n			",5883,6471);
$z[1][4]=array();
$z[1][4]['titlelen']="55";
$z[1][4]['orderby']="pubdate";
$z[1][4]['limit']="0,10";

?>