<?php
$z[0]=Array("global","",212,238);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("include","",1067,1102);
$z[1][4]=array();
$z[1][4]['filename']="head.htm";
$z[2]=Array("arclist","\n				<div class=\"item-subject item-subject-hot\">\n					<a href=\"[field:arcurl/]\" class=\"img\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\"></a>		<h3 class=\"title\"><a href=\"[field:arcurl/]\">[field:title/]</a></h3>\n					<p class=\"desc\">[field:description function='cn_substr(@me,250)'/]...</p>\n					<div class=\"attr\">\n						<span class=\"attr-author\">[field:writer/]</span>			<span class=\"attr-time\">[field:pubdate function=\"tranTime(@me)\" /]</span>\n						[field:id function=GetTags(@me)/]\n					</div>\n				</div>\n			",3461,4049);
$z[2][4]=array();
$z[2][4]['titlelen']="55";
$z[2][4]['orderby']="pubdate";
$z[2][4]['limit']="0,10";
$z[3]=Array("include","",5180,5216);
$z[3][4]=array();
$z[3][4]['filename']="right.htm";
$z[4]=Array("include","",6560,6597);
$z[4][4]=array();
$z[4][4]['filename']="footer.htm";

?>