<?php
$z[0]=Array("arclist","\r\n            <li>\r\n                <i class=\"dot\"></i>\r\n            	<a href=\"[field:arcurl/]\" target=\"_blank\"><span class=\"title\">[field:title/]</span></a>\r\n            	<div class=\"new_share\">\r\n					<div class=\"share_desc share_time\">\r\n						<span>[field:pubdate function=\"tranTime(@me)\" /]</span>\r\n					</div>\r\n					<div class=\"share_desc share_way\">\r\n						<span>分享至</span>\r\n						<div class=\"weixin weixin_top\">\r\n						<div class=\"code_top type_one\">\r\n							<div class=\"code_img\">\r\n								<img src=\"img/code.png\">\r\n							</div>\r\n							<div class=\"code_note\">\r\n								<p>打开微信扫一扫</p>\r\n							</div>\r\n						</div>\r\n					</div>\r\n						<div class=\"weibo\"></div>\r\n					</div>\r\n				</div>\r\n            </li>\r\n            ",697,1516);
$z[0][4]=array();
$z[0][4]['titlelen']="55";
$z[0][4]['orderby']="pubdate";
$z[0][4]['limit']="0,10";
$z[1]=Array("arclist","\r\n				<li>\r\n					<a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:title/]\">\r\n						<i class=\"num num-1\">1</i>\r\n						[field:title/]\r\n					</a>\r\n					<div class=\"new_share\">\r\n						<div class=\"share_desc share_time\">\r\n							<span>[field:pubdate function=\"tranTime(@me)\" /]</span>\r\n						</div>\r\n						<div class=\"share_desc share_way\">\r\n							<span>分享至</span>\r\n							<div class=\"weixin\">\r\n								<div class=\"code_desc\">\r\n									<div class=\"code_img\">\r\n										<img src=\"img/code.png\">\r\n									</div>\r\n									<div class=\"code_note\">\r\n										<p>打开微信扫一扫</p>\r\n									</div>\r\n								</div>\r\n							</div>\r\n							<div class=\"weibo\"></div>\r\n						</div>\r\n					</div>\r\n				</li>\r\n			",2839,3633);
$z[1][4]=array();
$z[1][4]['titlelen']="55";
$z[1][4]['orderby']="pubdate";
$z[1][4]['limit']="0,10";
$z[2]=Array("tag","\r\n				<a class=\"s2\" href=\"[field:link/]\" target=\"_blank\"><span>[field:tag /]</span></a>\r\n			",4181,4327);
$z[2][4]=array();
$z[2][4]['row']="32";
$z[2][4]['getall']="1";
$z[2][4]['sort']="month";

?>